### PR TITLE
Fix table list allow resizing table information #fixed

### PR DESCRIPTION
**Pull request by Jason-Morcos**
## Changes:
- Removed the odd black bar between table list and table information
- Allow resizing table information view

## Closes following issues:
- #477 

## Tested:
- MacBook Pro 2016
- macOS version: 11.0.1
- XCode version: 12.2

## Screenshots:
OLD:
Screen Shot 2020-11-22 at 11 04 14
NEW:
Screen Shot 2020-11-22 at 11 12 03

### CODE REVIEW

**Review by Kaspik — COMMENTED** [review]
The odd space there is that so if you hide the tabel info, the table list is not `under` the bottom actions bar... you would need to put the bottom bar into view with background. hm?

**Review by Kaspik — APPROVED** [review]
I can probably put the view below that

**Comment by Jason-Morcos** [comment]
I think then the whole split view should have space on the bottom, right? Now space in just the top panel? In other words, put the space at the bottom of a view higher up in the hierarchy

**Comment by Kaspik** [comment]
Weeeeell, yeah, maybe, maybe not... I'll try some things, let's merge this in the meantime. :)

**Pull request merged**
