### PR TITLE
Build Pods Automatically

### PR DESCRIPTION
**Pull request by Jason-Morcos**
I was unable to build 3.0 locally until making this change
It appears the pods were not being actually built in a build phase, therefore it would work but only if you built pods manually. This PR makes it part of build dependencies run phase to build pods

### CODE REVIEW

**Comment by Kaspik** [comment]
It should NOT build them. You need to run 'pod install' locally and then open xcworkspace instead of xcodeproj.

Any automated process is wrong because it doesn't guarantee that you use the same pods version as you should. Podfile.lock should be changed only manually after release and all PRs with that changed should be rejected. :)

**Comment by Jason-Morcos** [comment]
> It should NOT build them. You need to run 'pod install' locally and then open xcworkspace instead of xcodeproj.
> 
> Any automated process is wrong because it doesn't guarantee that you use the same pods version as you should. Podfile.lock should be changed only manually after release and all PRs with that changed should be rejected. :)

I understand the difference between pod update and pod install. I ran pod install. However, how does making building pods a dependency of the project have anything to do with incorrect versioning? In other words, what's the con of this PR? All of my apps are done this way. In none of them do I work with the workspace, only with the project. This isn't executing updates willy nilly, it's just requiring pods to get built as a build step. Does the workspace somehow magically build the pods? What's the reasoning for using the pod-created workspace in the first place?

**Comment by Kaspik** [comment]
It's the fundamental how Pods work - https://guides.cocoapods.org/using/using-cocoapods.html

Pods is separate project, that in the workspace is already linked to your project as a step. What you are doing is manual workaround to "hackyli" fix what worskapce is used for :)

Workspace itself gives you much more power in code-autoconplete, imports, builds steps, and also builds dependency graph od the projwct targets to increment build speed whereas your solution FIRST builds pods, then the project - that's way slower. :)

**Comment by Kaspik** [comment]
Sorry about the versioning, I first didn't get whatchu doing here :)

**Comment by Jason-Morcos** [comment]
Interesting! Today I learned! I've been doing it this way for literal years, since the advent of Cocapods lol. Now I guess I need to start using the workspaces!

**Comment by Kaspik** [comment]
Haha, happy to help! :))

**Pull request closed without merging**
