### PR TITLE
 #fixed Text is not invalidated if just a cut or paste action is executed

### PR DESCRIPTION
**Pull request by stefanfuerst**
## Changes:
editTextViewWasChanged  set to true if wasCutPaste is true

### CODE REVIEW

**Review by Kaspik — APPROVED** [review]
I'm not sure what this changes or what's the expected behavior / wrong behavior right now? More info would be welcome.

Overall looks good to me.

**Comment by stefanfuerst** [comment]
Paste something or cut from the editor - no typing. The change won't be saved.

**Comment by samuelbradshaw** [comment]
Does this fix https://github.com/Sequel-Ace/Sequel-Ace/issues/1595 and https://github.com/Sequel-Ace/Sequel-Ace/issues/1602?

**Comment by stefanfuerst** [comment]
> Does this fix #1595 and #1602?

Indeed.

**Comment by richbradshaw** [comment]
Thanks for this - was driving me insane!

**Pull request merged**
