### PR TITLE
Add bracket highlighter

### PR DESCRIPTION
**Pull request by pmarnik**
Please consider adding this implementation of matching brackets highlighting.

sequel_pro_bracket_hightlighting

### CODE REVIEW

**Comment by Jason-Morcos** [comment]
Hey there! This looks pretty cool! I don't see an option in the settings to enable/disable this feature though. Would it be possible to include that? I think some users may want to turn this off and I think we want to allow users to do so. Syntax highlighting may provide a good example of how to set up a preference for the query editor!

**Comment by stychos** [comment]
I agree about having possibility to disable this from preferences. Sometimes it's needed to work with a huge queries, and syntax highlighting going to be disabled for speed.

**Comment by pmarnik** [comment]
I've added option to "Preferences" which will allow to control enabling/disabling this feature.

**Comment by Jason-Morcos** [comment]
> I've added option to "Preferences" which will allow to control enabling/disabling this feature.

Awesome! Unfortunately, it looks like it's conflicting with the other pref change we just made. Would you be able to resolve?
Additionally, when committing changes to the .xib files, try to commit only the exact lines you modify (so revert changes to other parts of the file). Anytime you open an XIB it updates like the whole thing, so I usually revert all but the specific parts of the file in my client Sourcetree.

**Comment by pmarnik** [comment]
I've resolved conflicts. In preference pane I added only "Bracket highlighting" option. When I try to align it, then a lot of content in this file is changing.
Preferences 2020-09-21 22-16-17

**Comment by Jason-Morcos** [comment]
> I've resolved conflicts. In preference pane I added only "Bracket highlighting" option. When I try to align it, then a lot of content in this file is changing. Should I leave it as is (and you will adjust alignment after merge), or algin on my branch?
> 
> Preferences 2020-09-21 22-16-17

Hmmmm go ahead and try to align it! I'd rather have it lined up perfect, even if that means more changes

**Comment by Jason-Morcos** [comment]
Want to say, I really love this PR. I think this will be a feature that many of us will use and love.
One comment/request/note - It's a little hard to see the text with highlights in certain backgrounds. Would it be possible for the color to adjust dynamically and/or be customizable in the query editor themes? Definitely not a blocking thing for merging this PR, just a note.

Screen Shot 2020-09-21 at 20 08 01

**Comment by pmarnik** [comment]
I fixed the label in settings alignment. Additionally I modified a little bit highlight color, so it looks better on dark theme. 



Maybe in some future PR I will try to provide some better solution for color customization.

**Review by Jason-Morcos — APPROVED** [review]
Awesome work, @pmarnik!

**Comment by Kaspik** [comment]
Seems like there is an issue introduced most probably by this PR - https://github.com/Sequel-Ace/Sequel-Ace/issues/413

@pmarnik Would you mind taking a look?

**Comment by pmarnik** [comment]
I'm not able to reproduce #413 issue.

**Comment by Kaspik** [comment]
@pmarnik Sooo we have an issue here. We were able to get syntaxHighlight performance to really good state, but bracket highlighter is causing a lot of issues. Specifically:
`[self.bracketHighlighter bracketHighlight:caretPosition -1 inRange:currentQueryRange];` called in `SPCustomQuery`. If you import any SQL file so your query editor has for example 1000 lines, (simple `create
 command with values and some columns), it means your query editor can have 25000 characters. In that case, writing new query and adding `(` on line ~100 causes CPU to block main thread because it needs to go through 19 000 characters and find anything to highlight.

Any ideas what to do? We can also simply don't highlight code if the `currentQueryRange.length is more than 1000`, but ... wanted to first ask you about ideas.

**Comment by Kaspik** [comment]
Made a hotfix for now: https://github.com/Sequel-Ace/Sequel-Ace/pull/575/commits/540b7f6144c3c37e05fdf25c7c24ad2fa8ae3022

**Comment by pmarnik** [comment]
I have some ideas how to improve performance of bracket highlighting. I need to implement cache of comments locations.

**Comment by Kaspik** [comment]
@robinkunde had also a comment that for example Sublime limits num of characters it looks forward (https://forum.sublimetext.com/t/matching-bracket-limit/1852/2) - we could do that too. It doesn't make sense to highlight something that is out of screen, so not looking further than 2000 chars makes sense. What do you think?

**Comment by pmarnik** [comment]
@Kaspik I think that this limit is a good idea.

**Pull request merged**
