### PR TITLE
Update about panel look and constraints

### PR DESCRIPTION
**Pull request by robinkunde**
What does this implement/fix? Explain your changes.
---------------------------------------------------
I wanted to get a better feel for AppKit so I gave the About panel some upgrades:

* added autolayout
* moved to transparent title bar look
* release instance of window controller so it is deallocated when the panel is closed

### CODE REVIEW

**Comment by Jason-Morcos** [comment]
Can you throw on a screenshot so we can see what it'll look like without building locally? 😀

**Comment by robinkunde** [comment]
Screen Shot 2020-09-22 at 2 35 09 AM
Screen Shot 2020-09-22 at 2 35 17 AM
Screen Shot 2020-09-22 at 2 35 31 AM
Screen Shot 2020-09-22 at 2 35 34 AM

**Comment by Kaspik** [comment]
We really need to set the tint color to red from icon so it's not orange like on the screenshots. 😅
But evrything will happen!

**Review by Kaspik — APPROVED** [review]

**Comment by Jason-Morcos** [comment]
Just making sure, this builds with the release version of Xcode 12, yes? Apple is only accepting App Store submissions for Xcode 12 and not accepting Big Sur submissions yet so just want to make sure this doesn't block us from making App Store releases. I noticed the screenshots are Big Sur

**Comment by Jason-Morcos** [comment]
> Just making sure, this builds with the release version of Xcode 12, yes? Apple is only accepting App Store submissions for Xcode 12 and not accepting Big Sur submissions yet so just want to make sure this doesn't block us from making App Store releases. I noticed the screenshots are Big Sur

Just tested and it does and looks great! Awesome!

**Comment by robinkunde** [comment]
@Jason-Morcos I'm on Catalina. Why do you think it's Big Sur?

**Comment by Jason-Morcos** [comment]
> @Jason-Morcos I'm on Catalina. Why do you think it's Big Sur?

I think I got tricked up by Jakub's comment (because there some stuff in Big Sur about app colors) and just wanted to be extra careful about not committing beta stuff back to the repo because it's got me before and made me unable to release updates. But, indeed not Big Sur and looks great.

**Pull request merged**
