### PR TITLE
Fix double-check-before-delete feature #fixed

### PR DESCRIPTION
**Pull request by dnicolson**
## Changes:
- Make `createDefaultAlertWithSuppression` synchronous

## Closes following issues:
- Closes: #1074

## Tested:
- Processors:
  - [x] Intel
  - [ ] Apple Silicon
- macOS Versions:
  - [ ] 10.12.x (Sierra)
  - [ ] 10.13.x (High Sierra)
  - [ ] 10.14.x (Mojave)
  - [ ] 10.15.x (Catalina)
  - [x] 11.x (Big Sur)
- Localizations:
  - [x] English
  - [ ] Spanish
  - [ ] Other (please specify)
- Xcode Version:
   13.0 (13A233)

## Additional notes:
The problem is that the [NSAlert](https://github.com/Sequel-Ace/Sequel-Ace/blob/52be301/Source/Controllers/MainViewControllers/TableContent/SPTableContent.m#L1838) call was made asynchronous with https://github.com/Sequel-Ace/Sequel-Ace/pull/648.

The `createDefaultAlertWithSuppression` method is used only once, so this will fix the issue for now. The larger question is are asynchronous alerts needed at all?

### CODE REVIEW

**Comment by dnicolson** [comment]
That makes sense. In that case, the [preceding alert](https://github.com/Sequel-Ace/Sequel-Ace/blob/52be301/Source/Controllers/MainViewControllers/TableContent/SPTableContent.m#L1807) should also be async then?

**Comment by Jason-Morcos** [comment]
> That makes sense. In that case, the [preceding alert](https://github.com/Sequel-Ace/Sequel-Ace/blob/52be301/Source/Controllers/MainViewControllers/TableContent/SPTableContent.m#L1807) should also be async then?

It certainly could be, yes, but it doesn't necessarily have to be changed. I think we just need to make sure that if we're showing the extra confirmation we're not running the delete as if the extra confirmation is synchronous (because that's already moved to async).

**Comment by dnicolson** [comment]
Both alerts are displayed before the delete queries take place. The problem is that due to the async alert the result of the alert is set after it is checked [here](https://github.com/Sequel-Ace/Sequel-Ace/blob/52be301/Source/Controllers/MainViewControllers/TableContent/SPTableContent.m#L1851).

**Comment by Jason-Morcos** [comment]
> If the first alert being sync is acceptable then I would make the second alert sync as well (this pull request restores the previous sync behavior). Both alerts are displayed one after the other before any queries are performed.

The method `createDefaultAlertWithSuppression` should not be changed to be synchronous. The entire method is designed to be async. It takes in button handler callbacks, which makes little to no sense for a method that would be synchronous (it would just return a status/result code which would be handled on the other side).

While I have no issue with leaving the _existing_ synchronous modal as is, I wouldn't support adding _new_ synchronous modals. There's a big difference in my opinion between not altering legacy code that isn't introducing an error and writing new code in a legacy fashion. There's a happy middle-ground where things are moved over when they are buggy/written, but old things can stick around as long as they aren't causing issues.

**Pull request merged**
