### PR TITLE
Submit 2.1.6 to App Store

### PR DESCRIPTION
**Pull request by Jason-Morcos**
- Only show query warning when executing destructive operations (#160)
- Add a setting to choose between Auto/Dark/Light appearance modes (#284)
- Checkbox in preferences to display table comments in the list of tables (#286)
- Change "show mysql help for word" keyboard mapping to ⇧⌘H to remove conflict with ⌃H "delete" keystroke (#287)

### CODE REVIEW

**Comment by jamesstout** [comment]
Found an issue.
```sql
SHOW CREATE TABLE `wp_actionscheduler_actions`;

SHOW CREATE TABLE `wp_actionscheduler_actions`;

```

That would return yes for contains destructive SQL. The middle empty row is processed. Quick fix. Do we want it in this release?

**Comment by jamesstout** [comment]
`*googles Swift while loops*`

**Comment by julian-weinert** [comment]
> *googles Swift while loops*

Are there any plans to convert the complete project to Swift?
I'm really interested in contributing and really get on this project. But to be honest, It wouldn't be worth for me if the long term plans were a move to Swift

**Comment by Jason-Morcos** [comment]
> Found an issue.
> 
> ```sql
> SHOW CREATE TABLE `wp_actionscheduler_actions`;
> 
> SHOW CREATE TABLE `wp_actionscheduler_actions`;
> ```
> 
> That would return yes for contains destructive SQL. ~The middle empty row is processed~ The`\n`is prefixed to the third line.. Quick fix. Do we want it in this release?
> 
> Cause:
> 
> I originally added the NSString Obj-C category method:
> 
> ```objc
> - (NSString *)trimSubstringFromStart:(NSString *)needle
> {
> 	NSInteger needleLen = [needle length];
> 	NSString *str = self;
> 	while ([str hasPrefix:needle]){
> 		str = [str substringFromIndex:needleLen];
> 	}
> 	return str;
> }
> ```
> 
> But the swift version does't loop in dropPrefix:
> 
> ```swift
> func dropPrefix(_ prefix: String) -> String {
> 	guard self.hasPrefix(prefix) else {
> 		return self
> 	}
> 	return String(self.dropFirst(prefix.count))
> }
> ```

@jamesstout So sorry, I somehow missed this last week. Moved across the country so I was pseudo off the grid. I haven't submitted 2.1.6 yet, leaving the PR open to track changes up until submission. Has the issue been fixed in latest dev or do we still need to do some work on this?

**Comment by Jason-Morcos** [comment]
> Are there any plans to convert the complete project to Swift?
> I'm really interested in contributing and really get on this project. But to be honest, It wouldn't be worth for me if the long term plans were a move to Swift

Yes and no. There is absolutely no plan to convert the whole project to Swift. However, as Swift is absolutely the future of Apple development, newly created components and those heavily modified will likely be created in Swift. The project as it is today is a huge Objective-C project with only a few Swift classes. It is likely that someday the project will become primarily Swift and then Objective-C will be fully removed, however that day is not soon for sure.

**Comment by julian-weinert** [comment]
Oh, how sad to hear.
It's time to stop putting up with Apples shit. Why does nobody simply tell then their wrong doing and and not use it?
Now, doesn't matter how idiotic and senseless the idea is. Apple said, people do.

**Comment by jamesstout** [comment]
> @jamesstout So sorry, I somehow missed this last week. Moved across the country so I was pseudo off the grid. I haven't submitted 2.1.6 yet, leaving the PR open to track changes up until submission. Has the issue been fixed in latest dev or do we still need to do some work on this?

Fixed in dev by #280

**Pull request merged**
