### PR TITLE
Remove titleAccessoryView #removed

### PR DESCRIPTION
**Pull request by Kaspik**
## Changes:
- Remove titleaccessoryView as it's not used anyways anymore

## Closes following issues:
- Closes: Nothing

## Tested:
- Processors:
  - [ ] Intel
  - [x] Apple Silicon
- macOS Versions:
  - [ ] 10.12.x (Sierra)
  - [ ] 10.13.x (High Sierra)
  - [ ] 10.14.x (Mojave)
  - [ ] 10.15.x (Catalina)
  - [x] 11.x (Big Sur)
- Xcode Version:
- Localizations:
  - [x] English
  - [ ] Spanish
  - [ ] Other (please specify)
## Additional notes:
I have no idea what this view was supposed to do but I can't see it anywhere and I don't see a difference when removing it. It might improve https://github.com/Sequel-Ace/Sequel-Ace/issues/857

### CODE REVIEW

**Review by Jason-Morcos — COMMENTED** [review]
Looks okay, are we certain we're not using this to show the "SSH Connected" stuff? 
Let's hold until after the 3.2.3 release, just so we can test to make sure no funky edge cases before pushing. I'm pushing 3.2.3 to apple now

**Comment by Kaspik** [comment]
I have no idea, but iirc that was funky-broken too, right? 😂 Yeah I'm okay with merging tomorrow.

**Comment by Jason-Morcos** [comment]
> I have no idea, but iirc that was funky-broken too, right? 😂 Yeah I'm okay with merging tomorrow.

Screen Shot 2021-03-03 at 14 45 00
A little funky but still mostly working lol

**Comment by Kaspik** [comment]
Why would we be hiding it on full screen, and why do we have image there (in the xib) for this? 🤷🏻‍♂️

**Comment by Jason-Morcos** [comment]
> Why would we be hiding it on full screen, and why do we have image there (in the xib) for this? 🤷🏻‍♂️

Good point, looks like it indeed is just some silly legacy thing. Good to remove, next release :)

**Comment by Kaspik** [comment]
3.2.3 is out 🎉

**Pull request merged**
