### PR TITLE
[Work In Progress] GitHub Pages Documentation

### PR DESCRIPTION
**Pull request by stychos**
This pull request is related to https://github.com/Sequel-Ace/Sequel-Ace/issues/24

Documentation is got from https://sequelpro.com/docs and slightly adapted.

Work in progress for concepts review. Live [here.](https://stychos.github.io/Sequel-Ace/)

To do:

- [x] Launch GitHub Pages
- [ ] <del>Getting Connected Section</del> Revise!
- [x] Making Queries & Query Favorites Pages
- [x] Keyboard Shortcuts Page
- [ ] Reference Section
- [ ] Bundles Section
- [ ] Contribute Section
- [ ] Usage Screenshots
- [ ] Verify all in-app links
- [ ] Download from AppStore link

Looks like in `docs/` directory it works only from `master` branch.

### CODE REVIEW

**Comment by Jason-Morcos** [comment]
@stychos This is awesome!!! What an awesome first step, documentation-wise!

On the Getting Connected page, I believe this is no longer true with sandboxing world?
>In case you already have a SSH key saved on the remote machine, you can leave the SSH password field empty. Sequel Ace will create the SSH tunnel using that key.

**Comment by Jason-Morcos** [comment]
We should also be sure to add a nice big link to download from the App Store!

Also, prioritization-wise I would focus on the pages that are linked today from within Sequel Ace. It would be nice if 2.1.0 could point all documentation links at our in-house docs as opposed to https://www.sequelpro.com!

**Comment by Jason-Morcos** [comment]
Also @stychos, I purposely redirected your PR to master. Once we have some docs, I'd like to push them straight up and out. Especially so that we can change the links in the app and have the links work in betas prior to release of a new App Store version with proper documentation links!

**Comment by stychos** [comment]
You right, looks like we need to rewrite "Getting Connected" from scratch. Hope will finish with this on a week, I am not so fast as you, unfortunately :)

**Comment by Jason-Morcos** [comment]
The thing about documentation is it's really never finished haha. I think you've got a ton done and I would already feel comfortable publishing what you have so far and continuing to add onto it over time! So take your time, looking great to me so far!

**Comment by Jason-Morcos** [comment]
@stychos Would you mind if I merged this so that we could have multiple collaborators PRing for documentation (and could test the domain bought over the weekend)? We could create a project for the documentation and make some of these documentation tasks specific cards?

**Comment by stychos** [comment]
@Jason-Morcos yes sure, fixed things preventing GitHub Pages builds now, you can do that. Should I remove Draft status?

**Comment by Jason-Morcos** [comment]
Yup. Right now it doesn't show mergeable. Can you pull back from ace master to make sure it's merge safe?

**Comment by stychos** [comment]
Hm.. don't understand from where conflicts are came, especially when everything I touched is just ./docs/
Trying to resolve this.

**Comment by Jason-Morcos** [comment]
I think it's because we un-forked from sequel pro this AM. You may have to do some git craziness to get your branch to be "based" of sequel ace master

**Comment by stychos** [comment]
Aha, thanks for the pivot.

**Comment by stychos** [comment]
Going to recreate this.

**Pull request closed without merging**
