### PR TITLE
Initial Release (2.0)

### PR DESCRIPTION
**Pull request by Jason-Morcos**
- Dropped support for macOS < 10.10
- Apple Notarization
- True dark mode support (better colors in dark mode than Sequel Pro nightly build too, @Kaylanx, and better icons, @stychos)
- Remove Growl framework and switch to Apple Notification Center (to support notarization)
- Hardened runtime support (to support notarization)
- Fixes MacOS Catalina site selector random width bug (@corecoding)
- Fix incorrect layout when window is resized externally (@tweekmonster)
- Update clientid to use latest version of dpriver SQL formater (@vodatis)
- Fixes to main thread handling (@jamesstout)

### CODE REVIEW

**Comment by clayreimann** [comment]
Why the help wanted label on this?

**Comment by Jason-Morcos** [comment]
Hey there, @clayreimann! Two reasons:
1. I really do want this to be a collaborative project and encourage anyone to PR things for the 2.0 release.
2. This issue needs to be solved before Sequel Ace can be put on the Mac App Store and I've been unable to solve it (https://github.com/Sequel-Ace/Sequel-Ace/issues/10)

**Comment by Jason-Morcos** [comment]
@jamesstout 2.0 officially released on the macOS App Store! Now the work begins on 2.1 haha

**Comment by jamesstout** [comment]
Woah, it's on the store already! Just downloaded. Excellent stuff!

**Comment by kaylanx** [comment]
Nice, just downloaded too and sent a message to all developers at Booking.com Transport as we were heavy users of Sequel Pro, nice to have my change included too thanks :)

**Pull request merged**
