### PR TITLE
Convert SPMySQLFramework fully to ARC

### PR DESCRIPTION
**Pull request by Kaspik**
- convert SPMySQLFramework to ARC
- remove memory leaking methods

### CODE REVIEW

**Comment by Jason-Morcos** [comment]
Should this be aimed at main_3 or main?

**Review by Jason-Morcos — COMMENTED** [review]
Tested locally and seems to work! My only 10¢ would be to point this at the 3.0 release instead of 2.x.
Additionally, it seems like the loading indicator is almost sluggish? Like perhaps there is some synchronicity going on between the loading indicator and table load. Perhaps unrelated to this PR, but thought I would mention. Nice work!

**Comment by Kaspik** [comment]
Nah, I'm pointing this stuff to 2.x as there is nothing that won't work and there is no reason why not to improve the older version as well. :) If there would be some blocker, I'll switch to the 3.x, but for now I don't think we should be over-focused on that yet....

These small frameworks should be easy and not dangerous to convert, it will simplify the other PR, and should make no difference in actual product except maybe fixing some ARC bugs. :)

**Review by Jason-Morcos — APPROVED** [review]

**Comment by Jason-Morcos** [comment]
Sounds good! If we merge this, let's go ahead and bump the marketing version numbers to 2.3.0 (via agv) and rename the release PR.

However, we may want to fix that current ssh key issue and release another 2.2.x before doing 2.3.0. Idk

**Comment by Kaspik** [comment]
I would aim for 2.3.0 and ignore any 2.2.x, there is no breaking change that would block users from updating, so the SSH fix can go to 2.3.0 as well :)

**Pull request merged**
