### PR TITLE
Prepare and ship 3.0.0 beta 1

### PR DESCRIPTION
**Pull request by Kaspik**
# Major release of Sequel Ace is coming!

## This version comes with couple of breaking changes:
- Dropped support for MacOS 10.10 and 10.11
- Added support for Apple SIlicon, M1, ARM architecture (universal app)
- Converted project to ARC
- Rewritten how `SPTextView` and `Query` text view works to speed up large queries and syntax highlight
- Migrated from legacy `NSAlert` API and `NSApp.beginSheet()` to new `NSAlert`

### Added
cb74045b, kill tidb query and kill tidb connection support 
58fde57b, Compile libmysqlclient for Apple Silicon, enable ARM architecture, make Sequel Ace Apple Silicon compatible 

### Fixed
068622cc, Get rid of SPAlertSheets and fix over 150 warnings 
4db1f957, Main thread crashes  
3ef4e6ec, Fix couple of warnings and deprecations 
fd57651a, A couple of fixes  
395006b9, Fix broken add connection button 
12d1d8a8, Show alert on bad bundle, also actually delete it 
4ba2bc9f, Fix table list allow resizing table information 
6944d8d8, Fix close button style on tabs 
d58d3a93, Fix Query ruler view and rows count 
2e0af572, Speedup loading list of the tables 

### Changed
db395c51, SPTextView: Rewrite behavior of syntax highlight and scroll 
52af9e8f, SPTextView improvements and warnings 
c3733542,  ShortcutRecorder converted to ARC and ARM
007e82a7, Rewrite appearance for split view actions - part 2 
a66c083f, Rewrite appearance for settings toolbar, database toolbar and split view actions 

### Infra
cc27ecb1, Tweak issue and pr templates 
6f87e6cb, Fix Beta Scheme 
fa2e2e83, Add fastlane automation for increment_build and for Changelog generation 
363bb954, Add Swiftlint to the project

### CODE REVIEW

**Comment by Reached** [comment]
@Kaspik great work! Is it possible to test the beta yet? :)

**Comment by Kaspik** [comment]
Beta are available to download and test in Releases - https://github.com/Sequel-Ace/Sequel-Ace/releases
There will be a new one today. :)

**Comment by Reached** [comment]
Amazing, thank you!

**Comment by Reached** [comment]
Just wanted to say that the beta has worked really well for me on my Macbook Air M1, so well done :)!

**Comment by Kaspik** [comment]
Glad it works! I'm really happy we were able to build all libs and frameworks into universal libraries so quickly and we are about to release both Intel and M1 version for Christmas! :)

**Comment by Reached** [comment]
Well done!

**Pull request merged**
