### PR TITLE
Update readme with Homebrew installation support

### PR DESCRIPTION
**Pull request by Kaspik**
Improves https://github.com/Sequel-Ace/Sequel-Ace/issues/58

- remove build info - this was in Sequel-Pro so people could build master project
- add Homebrew info
- update styling

Screen Shot 2020-06-22 at 22 34 27

### CODE REVIEW

**Comment by Jason-Morcos** [comment]
Love it. Would it be worth keeping the build info under the contributing section to help newcomers know how to get started?

**Comment by Kaspik** [comment]
I'm not sure about that. People that want to contribute to such a complicated (bug in this app can cause issues for millions of users if it breaks prod. database) project should know how to clone a repo and open a XCode project, what do you think?

**Comment by Jason-Morcos** [comment]
> I'm not sure about that. People that want to contribute to such a complicated (bug in this app can cause issues for millions of users if it breaks prod. database) project should know how to clone a repo and open a XCode project, what do you think?

Hmmm they should know, but on the other hand we never want to have a barrier to entry for someone to start playing with something, if only locally. I could go either way! Can let others chime in.

**Comment by juniorb2ss** [comment]
Is it expected to close the issue #58?

The way to install using `mas` is great, however, it also requires another library. The interesting thing is to keep the issue open until we can install it directly through the cask.

What you think?

**Comment by Kaspik** [comment]
Not close, we will leave it open. :)

**Comment by juniorb2ss** [comment]
Thank you guys. I'm very happy to see this project still in progress. Nice job.

**Pull request merged**
