### PR TITLE
Changes on the icon discussed on issue #31 

### PR DESCRIPTION
**Pull request by vinilanzoni**
What does this implement/fix? Explain your changes.
---------------------------------------------------
Changes on the icon discussed on issue #31 

Does this close any currently open issues?
------------------------------------------
#31

### CODE REVIEW

**Comment by Jason-Morcos** [comment]
Hey @vinilanzoni! Love the work you've been doing. When I open the icon psd it appears that the icon is rasterized. Would it be possible to share the icon in a vector format? When I slice the image into different sizes (for all the different sizes apple requires) it looks a lot better if the icon is vectorized instead of raster. Could be an affinity designer file or svg or illustrator or really any vector format!

**Comment by vinilanzoni** [comment]
@Jason-Morcos, what psd file you are trying to open?
Using the **Template - Icon - App.psd** you can export directly from Photoshop into final png icon using _File > Generate > Image assets_
I don't have the vector format. I did all the shapes in Photoshop.

**Comment by Jason-Morcos** [comment]
The icon.psd file. I use affinity designer, but it has all the same features as photoshop.

Ahh I see, hmmm. Well then we'll probably have to figure out how to recreate the design in vector format. It's just gonna look a little blurry using rasterized images and slicing them

**Comment by vinilanzoni** [comment]
I added the PNGs under _assets_ folder

**Comment by Jason-Morcos** [comment]
The issue with raster icons is the error which will be exaggerated by each additional slice. The icon won't look quite perfect. This is a screenshot of part of the 1024 slice from the PR.
Screen Shot 2020-06-28 at 14 58 12

I think I have it redesigned as a vector icon. At least this is pretty close (not identical) to what you have. Do you have affinity designer?

Icon

**Comment by Jason-Morcos** [comment]
https://github.com/Sequel-Ace/Sequel-Ace/blob/dev/Artwork/Icon%202.afdesign

**Comment by kingkool68** [comment]
Just here to say I really dig the new logo. Much sleeker.

**Pull request closed without merging**
