### PR TITLE
Major change: Rewrite fonts to use selected font across the app

### PR DESCRIPTION
**Pull request by Kaspik**
What does this implement/fix? Explain your changes.
---------------------------------------------------
- Move font settings to General tab of Preferences instead of Table tab
- Remove Monospace settings
- Change all tables to use specified font, use secified font in content, structure, favorites, indexes and other places
- Default to System font of size 11
- Allow app to realtime change the font when changed in Preferences
- Autolayout for connection view!!
- fix not calling super for observers

Does this close any currently open issues?
------------------------------------------
https://github.com/Sequel-Ace/Sequel-Ace/issues/233

Where has this been tested?
---------------------------
**Devices/Simulators:** iMac 5K
**macOS Version:** Big Sur 11.0.1 Beta

### CODE REVIEW

**Review by Jason-Morcos — CHANGES_REQUESTED** [review]
I think a few of these removed features are actually useful. The option for monospaced fonts in the table view is helpful if you're looking at certain types of data (hex) and trying to line everything up. Additionally, I think we should let people select a different font for the table view contents themselves. I think that's a nice feature. We could make it by default fallback on the primary font and only use the table font if specified?

Additionally, this PR introduces a bug with connection name truncation. I think we saw this last time we tried to mess with connection name font?
Screen Shot 2020-10-30 at 09 35 09

Table names are also truncated for me
Screen Shot 2020-10-30 at 09 36 04

**Comment by Jason-Morcos** [comment]
Additionally, does changing the font size of the table content not increase the font size of the table list?
I work with a guy with not-the-best vision and his biggest gripe about Ace is that the table list font size is small and tough for bad eyes.
Screen Shot 2020-10-30 at 09 37 30

**Comment by Kaspik** [comment]
> I think a few of these removed features are actually useful. The option for monospaced fonts in the table view is helpful if you're looking at certain types of data (hex) and trying to line everything up. Additionally, I think we should let people select a different font for the table view contents themselves. I think that's a nice feature. We could make it by default fallback on the primary font and only use the table font if specified?
> 

You can change the font to whatever you want, if you want monospaced, then choose it - that's the main point of this - this gives total freedom to everyone. :)

**Comment by Kaspik** [comment]
> Additionally, does changing the font size of the table content not increase the font size of the table list?
> I work with a guy with not-the-best vision and his biggest gripe about Ace is that the table list font size is small and tough for bad eyes.
> Screen Shot 2020-10-30 at 09 37 30

It does, weird it doesn't happen for you...

**Comment by Kaspik** [comment]
Lol I forgot to listen on tables list... fixed. Can't repro the cell size.

**Comment by Jason-Morcos** [comment]
Putting this on here so all can see - getting a crash if I connect to a DB and try to click on a table (to see its contents)
Screen Shot 2020-10-31 at 15 59 46

**Comment by Jason-Morcos** [comment]
> Putting this on here so all can see - getting a crash if I connect to a DB and try to click on a table (to see its contents)
> Screen Shot 2020-10-31 at 15 59 46

Debugging a bit, the error is ```Thread 1: "The window has been marked as needing another Update Constraints in Window pass, but it has already had more Update Constraints in Window passes than there are views in the window."```

Apparently it can happen with infinite recursion view updates?

**Comment by Jason-Morcos** [comment]
@Kaspik I spent a not insignificant amount of time adding auto layout to the connection view to try to resolve all the issues with shortened text and such. Do we think we could try to fix issues with that (which we already know there were layout issues with connection view) rather than revert those changes? I mean it was like many hours of time to get the layout all working. While clearly there is some issue, I would really rather try to fix that issue than undo all those changes to auto layout which did fix issues with this PR (text truncation).

**Comment by Kaspik** [comment]
I'm trying to resolve ehy favorites outlinwd view is not full size of the left side bar in split view - but TLDR - we can't use autolayout on connection view. Unfortunately split view is shared across multible nibs (wrong) - so the same split view that uses autolayout for connection view then tries to use autolayout on the rest of the app after we dismiss connection view... which means we would need to convert to auto layout the DBView.xib as well - which I don't think we can...

I know you spent a whole lot of time on that (we can revert the revert again) - but my idea for now was:
- fix outlined view width - even havky manually somehow
- convert the outline view to table view - it's the only table that is not table view, and it should be
- revert back the autolayout you did but move connection view out of the split view and use it as a separate window...

I'm not done yet and I'm not throwing your work - don't worry! :)

In case you have a time - feel free to try anything!

**Comment by Kaspik** [comment]
Soo after couple more hours here is my final decision:
- merge this as it is and put into release notes "Known issue: Favorites on connection view might get cut off. Please resize favorites sidebar to get this fixed." as Apple does into releases
- in separate PR - use @Jason-Morcos 's autolayout again - and move connection view to separate window OUT of the split view for next PR and release

I don't think doing 2) in this PR is what we should do - it's quite significant change, and I believe this PR is not release blocker - everything works, you just sometimes get your favorites cut off if they are too long. Merging this to main. :)

**Pull request merged**
