### PR TITLE
Fix foreign-key navigation

### LINKED ISSUE #54: Navigating using foreign keys is not working
### Environment:
Sequel Ace Version: 2.0.1 Build 2029
macOS Version: 1.15.4
MySQL Version: 5.6.28
### Description
Linking and navigating isn't working .. copy of issue [#3491](https://github.com/sequelpro/sequelpro/issues/3491) in Sequel Pro

### Steps To Reproduce:

- Go to any table with a foreign key 
- Click the foreign key (little arrow)
- Expected Behavior:
    It used to take you to the related table and show the selected index only, now it only opens the table

### Additional Context:

This used to work fine in Sequel Pro 1.1.2, it was soooo helpful.

Please bring it back

### PR DESCRIPTION
**Pull request by gboudreau**
What does this implement/fix? Explain your changes.
---------------------------------------------------
Fixing navigation using foreign-key arrows.

Does this close any currently open issues?
------------------------------------------
Fixes #54

Note
----
Select `Hide whitespace changes` to review.
image

### CODE REVIEW

**Comment by Jason-Morcos** [comment]
This fix is sorta working for me, but if I jump from one table to another (really big) table, it doesn't scroll me to the specific foreign key I selected - it selects it, but I have to scroll to find it. Would it work to set the filter bar itself to constrain to the appropriate value so you don't have to scroll at all?

Additionally, not sure if it was this fix that did it, but I seem to have lost my ability to navigate forward/back?
Screen Shot 2020-06-24 at 09 32 27

**Comment by gboudreau** [comment]
I fixed the scrolling.
But the history is something else... I need to find the right place to end `SPHistoryController` modifying state, in order to allow history to continue to be tracked.

**Comment by gboudreau** [comment]
I decided to create a new property (`navigatingFK`), instead of using the existing `modifyingState`, and possibly breaking something.

**Comment by gboudreau** [comment]
My tests: 
Screen Recording 2020-06-24 at 11 06 58 AM

**Comment by Jason-Morcos** [comment]
Working _almost_ 100% for me. The only problem I have is if I try to click through on a foreign key that exceeds the standard shown region, it's not visible. In other words, if I try to see thingy 1002, because the table only shows the first 1000 items I can't see the one I'm looking for. The view is showing only rows 1-1000 from the big table, and I clicked on a foreign key for row 1001+.
Does that make sense?

**Comment by gboudreau** [comment]
Yes, I understand. I think I saw code that changed pages somewhere in that file. Might need to trigger that.
If it's too complicated, I'll switch back to using filters... I prefer selection, because one might be interested in seeing other rows "around" the selected one, for example in a domain table...
But if the code becomes too complicated because of that, filter might be a better option.

**Comment by gboudreau** [comment]
Switched back to using filters. Finding the right page is not really possible (easily/quickly enough)...

**Pull request merged**
