### PR TITLE
Updated libmysqlclient to 8.0.20

### LINKED ISSUE #32: MySQL 8.0.20 connection error
- Sequel Ace Version: 2.0.1
- macOS Version: 10.15.5
- MySQL Version: 8.0.20

**Description**
Couldn't to connect with MySQL 8.0.20 version

**Steps To Reproduce**
1. Open Sequel Ace
2. Type credentials
3. Test connection
4. An error message with unknown error code appears:
Screenshot 2020-06-21 at 14 39 25

**Expected Behaviour**
A successful message should be displayed

**Additional Context**
The database is running inside a docker container.

### PR DESCRIPTION
**Pull request by gboudreau**
Updated libmysqlclient.a, and the related includes.
Had to make a few tweaks to the code.
libcrypto.1.1 and libssl.1.1 libs had to be added, and it took me a while to be able to include them, and make it so the SPMySQL framework would be able to load them at run time... Not sure why it was so complicated!

I didn't test if this effectively fixes the connection issues with MySQL 8, but it uses the latest version of the client library from MySQL.

Is someone has a MySQL 8.0 with SSL available to test, please do.

Possibly fixes #32

### CODE REVIEW

**Comment by Jason-Morcos** [comment]
Awesome!!
Let's wait to merge this until 2.0.2 with critical bug fixes is released (pending App Store review now). Prior to that, let's try to figure out if this indeed does fix the SSL connection issue or not (at least so we know).

I don't really have a way to test MySQL 8.0 SSL so I definitely second the wanting someone with MySQL 8 to test notion.

**Comment by Jason-Morcos** [comment]
Changed my mind a little big - Decided to create a staging branch which holds pending App Store releases. I'm good to start work on 2.1.0 so we can merge this to dev whenever we feel comfortable with it!

**Comment by gboudreau** [comment]
I tested using a docker MySQL 8 instance:

    docker run --rm --name mysql8 -e MYSQL_ROOT_PASSWORD=patate123 -p 3306:3306 mysql:8

I can connect with and without SSL.

I also confirmed I was really connected using SSL:
image

Sequel Pro chokes on the password if I try to connect to that MySQL without SSL, and with SSL, it gives the `unknown error number` error.

I think we're good to merge.

**Comment by Jason-Morcos** [comment]
Awesome! Let's merge! Will have some time to test more before 2.1.0 is out anyways

**Comment by Jason-Morcos** [comment]
Bumped dev to 2.1.0 version and confirmed that these changes don't seem to break anything for me with mysql <8!

**Comment by jamesstout** [comment]
Excellent. I was attempting it last night:

Screenshot 2020-06-22 at 2 19 46 PM

**Pull request merged**
