### PR TITLE
Update Readme.md install instructions

### LINKED ISSUE #58: Can we have .dmg file on releases download page?
That can be good to create a cask formule for `brew`, like we have today for `sequel-pro`: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/sequel-pro.rb

### PR DESCRIPTION
**Pull request by plessbd**
What does this implement/fix? Explain your changes.
---------------------------------------------------
Updates readme.md with how to install via `brew`

Since the instructions didn;t actually say how to do this with macports I removed the mentioning of macports

I don;t think this should say how to install mas (that should be up to mas)

Added the homebrew cask information

Does this close any currently open issues?
------------------------------------------
kind of closes #58 as the first stated request was for it to be used by homebrew.

### CODE REVIEW

**Comment by Jason-Morcos** [comment]
We are not maintaining the Sequel Ace Hombew cask. I honestly don't know who is distributing it and I'm unwilling to endorse something that we don't actually distribute.
@Sequel-Ace/all Does anyone know who is creating that Cask? Can we remove it and create our own?

**Comment by Kaspik** [comment]
Not me.

**Comment by stychos** [comment]
According to commit, looks like the Cask' author is [Homebrew](https://github.com/Homebrew) member @ran-dall: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/sequel-ace.rb

**Comment by plessbd** [comment]
a lot of casks are maintained by the community.  homebrew allows anyone to create a cask I am not seeing anything specific in their documentation that allows "ownership" of a cask.  The cask isnt really a distribution.  It is just a link to the zip file (and sha of it) in the releases that you guys are maintaining.

**Comment by Jason-Morcos** [comment]
> a lot of casks are maintained by the community.  homebrew allows anyone to create a cask I am not seeing anything specific in their documentation that allows "ownership" of a cask.  The cask isnt really a distribution.  It is just a link to the zip file (and sha of it) in the releases that you guys are maintaining and to me in that respect is the same as having a link the the AppStore.
> 
> 
Interesting, is there anything that ensures that the link will always point at our releases and can't be pointed at a malicious executable when someone comes in and updates the cask again later? That's my primary concern, particularly as Sequel Ace is a database tool which people may use to access private information.

**Comment by plessbd** [comment]
Usually the maintainers of homebrew will notice that the link is no longer the same domain and question it (at least at some point I have seen that in their repo) according to https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md it also looks like you can put a comment in that says something along the lines of "https://github.com/Sequel-Ace/Sequel-Ace is the official repository for this cask" as well as the homepage url being in the cask.

**Comment by plessbd** [comment]
Also, if you want you can request to not have sequel-ace in homebrew cask https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md

**Comment by Jason-Morcos** [comment]
> Usually the maintainers of homebrew will notice that the link is no longer the same domain and question it (at least at some point I have seen that in their repo) according to https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md it also looks like you can put a comment in that says something along the lines of "https://github.com/Sequel-Ace/Sequel-Ace is the official repository for this cask" as well as the homepage url being in the cask.

If we can get that comment added to the cask, and can slightly tweak this PR to say something along the lines of "An Unofficial GitHub Cask is also available", I'd be fine merging this PR

**Comment by ran-dall** [comment]
Sorry guys, for some reason I didn't see your mentions. Let me clear up a few things about HBC for you.

> According to commit, looks like the Cask' author maintainer is Homebrew member @ran-dall

It's true that I do a lot in HBC but it's a whole group that deserved the credit; including @vitorgalvao, @core-code, @suschizu, and @miccal.

> a lot of casks are maintained by the community.

This is true in theory but in reality the 'community' has a spotted records for updating things, this is why I built an Machine Learning-based system to do the most of the updates auto-magically, once a day.

> is there anything that ensures that the link will always point at our releases and can't be pointed at a malicious executable when someone comes in and updates the cask again later?

@core-code and I do manual malicious checks every now and again. That said, the updates done by the ML are ran also through Malice (when it decides to work correctly, it has some issues; some casks more than others).

> If we can get that comment added to the cask, and can slightly tweak this PR to say something along the lines of "An Unofficial GitHub Cask is also available", I'd be fine merging this PR

It is theoretically possible, however we try not to add too much extra stuff to the casks. If you'd (@Jason-Morcos) like, I can make the PR in HBC and we can see what the other maintainers think about it. Just let me know...

**Comment by samuelbradshaw** [comment]
It looks like the cask does have a link back to this repository:
https://github.com/Homebrew/homebrew-cask/blob/master/Casks/sequel-ace.rb

**Comment by Kaspik** [comment]
We can take a look on the automation, in the meantime, I don§t see a reason why hold this any longer, let's just ship it! :)

**Review by Kaspik — APPROVED** [review]

**Comment by suschizu** [comment]
> If we can get that comment added to the cask, and can slightly tweak this PR to say something along the lines of "An Unofficial GitHub Cask is also available", I'd be fine merging this PR

hey @Jason-Morcos - if this is an unofficial repository we should perhaps delete the cask - just give me a note :) (https://github.com/Homebrew/homebrew-cask/pull/85028)

**Comment by Kaspik** [comment]
This is official repo, I think there was some miss-understanding @suschizu :)

**Comment by vitorgalvao** [comment]
> I am not seeing anything specific in their documentation that allows "ownership" of a cask.

This is correct. No one maintainer is the arbiter of any single cask. There isn’t a need for that; casks are simple enough that even a non-coder can understand the important parts of most casks and check if something fishy is going on (e.g. a suspicious download URL).

> according to https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md it also looks like you can put a comment in that says something along the lines of "https://github.com/Sequel-Ace/Sequel-Ace is the official repository for this cask"

No. The comment you’re referring to has specific phrasing and [has a specific reason to be present](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/url.md#when-url-and-homepage-hostnames-differ-add-a-comment). It’s both for users to know that at one point maintainers made sure that URL was legitimate and for our CI to notice if it changes to something else, so we’re aware.

> Interesting, is there anything that ensures that the link will always point at our releases and can't be pointed at a malicious executable when someone comes in and updates the cask again later?

Human review. Any PR that changes the URL line will have to go through it.

> It looks like the cask does have a link back to this repository:
> https://github.com/Homebrew/homebrew-cask/blob/master/Casks/sequel-ace.rb

Casks in the main repositories use official sources. We accept nothing else.

> Perhaps (if it's even possible) it would be cool to automate PRs to casks each time we release a new version

[Easy](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask). You only need a short setup once, and after that a one liner every time there’s an update: `cask-repair --cask-version '<NEW_VERSION_HERE>' sequel-ace`. Assuming your URL pattern stays the same, that will take care of everything, including sending the PR to us.

**Pull request merged**
