### PR TITLE
UI enhancements: Update side bar cells in split views

### PR DESCRIPTION
**Pull request by Kaspik**
- resize cells in split views in sidebar - old values were designed for smaller resolutions and smaller screens
- fix margins and paddings inside the cell so more text fits
- stop using specific font size and leave it up to the system

Screen Shot 2020-06-28 at 19 07 07

### CODE REVIEW

**Comment by Jason-Morcos** [comment]
The ellipsis truncation is also happening for connections too
Screen Shot 2020-06-29 at 13 47 16

**Comment by Kaspik** [comment]
This has nothing to do with Big Sur yet, it's just update for modern devices, but I forgot to push one more commit to remove the offset for views.

**Comment by Kaspik** [comment]
Re: Truncating - I', not able to repro nor I think I touched that, I didn't do anything with truncation...

**Comment by Jason-Morcos** [comment]
Views issue definitely fixed!

But the truncating is definitely still there for me and emerged in your branch
Screen Shot 2020-06-29 at 15 27 23

**Comment by Kaspik** [comment]
@Jason-Morcos Can you try now? I have no idea why this would cause an issue, but let's see. Still not able to repro ...

**Comment by Jason-Morcos** [comment]
@Kaspik Unfortunately still truncating in both the favorites and table list views... Strange. Confirmed again the issue is not present on dev but emerges when switching to this branch

**Pull request merged**
