### PR TITLE
#Added New option to exclude GENERATED columns from SQL export

### PR DESCRIPTION
**Pull request by gduh**
## Changes:
- Adds an option to include GENERATED columns for SQL export. By default the option  is disabled, so data won't be included in the export until the user checks it. In any case, the `create table` SQL command always includes the field definition.
I do this change only for SQL export. I think it's not helpful for CSV, but for XML I'm not sure. 
GENERATED column is a new future since MySql 5.7 (2015).

## Closes following issues:
- Closes:  #1041

## Tested:
- Processors:
  - [X] Intel
  - [ ] Apple Silicon
- macOS Versions:
  - [ ] 10.12.x (Sierra)
  - [ ] 10.13.x (High Sierra)
  - [ ] 10.14.x (Mojave)
  - [X] 10.15.x (Catalina)
  - [ ] 11.x (Big Sur)
- Localizations:
  - [X] English
  - [ ] Spanish
  - [ ] Other (please specify)
- Xcode Version: 12.4 (12D4e)
  
## Screenshots:

GraphiqueCollé-1

### CODE REVIEW

**Review by Jason-Morcos — APPROVED** [review]
Looks good to me! Would like to let @Kaspik take a look too

**Comment by Kaspik** [comment]
Do we still wanna merge this with the new #1065 issue?

**Comment by Jason-Morcos** [comment]
I think merge this and also solve the #1065 issue in a future PR. @gduh Are you working on a fix to #1065? I agree it would be very nice to display which columns are generated

**Comment by gduh** [comment]
> I think merge this and also solve the #1065 issue in a future PR. @gduh Are you working on a fix to #1065? I agree it would be very nice to display which columns are generated

@Jason-Morcos Yes, I'm working on it !

**Pull request merged**
