### PR TITLE
Make filesystem match organizer

### PR DESCRIPTION
**Pull request by clayreimann**
What does this implement/fix? Explain your changes.
---------------------------------------------------
No functional changes here, but it organizes file in the repo as they appear in XCode

Does this close any currently open issues?
------------------------------------------
No

Any relevant logs, error output, etc?
-------------------------------------
No

Any other comments?
-------------------
No

Where has this been tested?
---------------------------
**Devices/Simulators:** Build locally 

**macOS Version:** 10.15.6

**Sequel-Ace Version:** current

### CODE REVIEW

**Comment by robinkunde** [comment]
By any chance, does this also check for source files that are in the repo but not part of the Xcode project?

**Review by Jason-Morcos — APPROVED** [review]
Looks good to me! Why not give it a go!

**Comment by clayreimann** [comment]
@robinkunde I just checked and the only files left in the Sources directory are the bridging headers and `main.m`

@Jason-Morcos cool, what's the process for merging?

**Comment by Jason-Morcos** [comment]
I'll just go ahead and merge it! Just wanted to let you answer @robinkunde first

**Pull request merged**
