### PR TITLE
#fixed  DEFAULT value of DATETIME is wrong

### PR DESCRIPTION
**Pull request by xlight**
try to fix issue: https://github.com/Sequel-Ace/Sequel-Ace/issues/1566

sorry .I have not tested the code, because I don't have a XCode environment.

### CODE REVIEW

**Review by Jason-Morcos — CHANGES_REQUESTED** [review]
Can you create a set of steps that don't work with the app as is but do work with this change? In other words, can you specify what the test plan should be (including a create table statement creating a table that shows this issue)?

**Comment by xlight** [comment]
> Can you create a set of steps that don't work with the app as is but do work with this change? In other words, can you specify what the test plan should be (including a create table statement creating a table that shows this issue)?

step:
1. create table
```
CREATE TABLE `test_datetime` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'id',
  `you_can_not_modify_me` datetime DEFAULT '2022-01-01  00:00:00' ,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB;
```

2. try to modify the column  `you_can_not_modify_me` from Structure tab. 
3. the Sequel show error 
image

the SQL string shows in pic above , has an error in SQL syntax. 
```
ALTER TABLE `test_datetime` CHANGE `you_can_not_modify_me` `you_can_not_modify_me` DATETIME
NULL
DEFAULT 2022-01-01 00:00:00
COMMENT 'add some comment'
```

should be :
```
ALTER TABLE `test_datetime` CHANGE `you_can_not_modify_me` `you_can_not_modify_me` DATETIME
NULL
DEFAULT '2022-01-01 00:00:00'
COMMENT 'add some comment'
```

**Comment by Jason-Morcos** [comment]
Hey @xlight,
Following your test procedure I can indeed see the bug in the current release. However, I also still see the same bug when running your PR locally. It doesn't appear that this fully fixes the issue

**Comment by Jason-Morcos** [comment]
This appears to fix it! https://github.com/Sequel-Ace/Sequel-Ace/pull/1661

**Pull request closed without merging**
