### PR TITLE
Add String extension with prefix and suffix operations

### PR DESCRIPTION
**Pull request by Kaspik**
- in favor of https://github.com/Sequel-Ace/Sequel-Ace/pull/244 and discussion about extensions - there is no reason to add Objective-C extensions anymore if Swift can do this nicely

### CODE REVIEW

**Comment by Jason-Morcos** [comment]
@Kaspik @jamesstout Does this need to be merged and then we modify #244 or what's the proper action here?

**Comment by Kaspik** [comment]
Yeah I'll add them tomorrow, probably in Swift as well.

**Comment by jamesstout** [comment]
> @Kaspik @jamesstout Does this need to be merged and then we modify #244 or what's the proper action here?

I think I need to update #244.

Do we have the tests?

**Comment by Kaspik** [comment]
Yes, #244 is no ready to be updated.

We don't yet, if you want, include them of course! :) Otherwise I'll do it asap once I have some time.

**Comment by jamesstout** [comment]
hmmm .. I get a bad access on dropPrefix

`[query setString:[query dropPrefix:@" "]];`

Some weird looping .. dropPrefix is called about 10000 times.....

**Comment by Kaspik** [comment]
hmm, I tried that without any issue... but it could be that NSString is calling the NSString extension which is not calling the String extension but again the NSString one? (I tried it in Swift when I started writing Swift tests)

**Comment by jamesstout** [comment]
#244 updated.

**Pull request merged**
