### PR TITLE
- New icon suggestion

### PR DESCRIPTION
**Pull request by tancredolt**
What does this implement/fix? Explain your changes.
---------------------------------------------------
I designed a new icon for the application and files, I'm sending the icons and the base file in .ai

Does this close any currently open issues?
------------------------------------------
No

Any relevant logs, error output, etc?
-------------------------------------
No

Any other comments?
-------------------
No

Where has this been tested?
---------------------------
**Devices/Simulators:** …

**macOS Version:** Catalina (10.15.5)

**Sequel-Ace Version:** 2.1.0

### CODE REVIEW

**Comment by Jason-Morcos** [comment]
Very cool effect with the text wrapped around the edges.

Have you seen the new app icon which just officially launched today (spent the last bit in beta)? And seen the discussion in #31?
Screen Shot 2020-07-06 at 21 58 41

I think we probably won't be making a change to the icon right away again in the short term but certainly appreciate the hard work!

**Comment by Kaspik** [comment]
@Jason-Morcos Should we also check and use the file icons, or update them with our new icon?

**Comment by Jason-Morcos** [comment]
> @Jason-Morcos Should we at least check and use the file icons, or update them with our new icon?

We did update the file icons with our new icon in the previous release. These icons are certainly cool, I just think we don't want to cycle through icons super quickly. Bad for user experience

**Comment by Kaspik** [comment]
Ohh I didn’t know we did it also for files, cool! :)

**Comment by tancredolt** [comment]
@Jason-Morcos I just saw the new icon yesterday,  it's a nice icon by the way, and congratulations and thanks for taking this app alive again!!

**Pull request closed without merging**
