### PR TITLE
Rewrite appearance for settings toolbar, database toolbar and split view actions #changed

### PR DESCRIPTION
**Pull request by Kaspik**
First major improvement in UI for Sequel Ace is here!

## Preferences:
Until now Preferences looked like this:
Screen Shot 2020-11-20 at 14 52 47

New preferences looks like this:
Screen Shot 2020-11-20 at 14 58 09

For Big Sur, we are already switching to SF Symbols, so new preferences for Big Sur only looks like this:
Screen Shot 2020-11-20 at 15 10 13

## Split view actions:
Connections view used our custom super-small PNGs, so it was changed to use native icons (bottom is old one):
Screen Shot 2020-11-20 at 14 46 37

Database view under the table list went through the same change:
Screen Shot 2020-11-20 at 14 46 55

## Main database toolbar:
toolbar for Big Sur:
Screen Shot 2020-11-20 at 23 00 12

## Console action toolbar
Screen Shot 2020-11-20 at 23 31 05

### CODE REVIEW

**Comment by samuelbradshaw** [comment]
Nice!

**Review by Jason-Morcos — APPROVED** [review]
To say I love this would be a tremendous understatement. Nice work!!

**Comment by Jason-Morcos** [comment]
Looks like tests are failing. If you can get tests passing definitely good to merge!

**Comment by Kaspik** [comment]
Rewritten also main toolbar for Big Sur:
Screen Shot 2020-11-20 at 23 00 12

**Pull request merged**
