### PR TITLE
Fixed more warnings

### PR DESCRIPTION
**Pull request by jamesstout**
What does this implement/fix? Explain your changes.
---------------------------------------------------
Fixed more warnings

Does this close any currently open issues?
------------------------------------------
…

Any relevant logs, error output, etc?
-------------------------------------

Any other comments?
-------------------
…

Where has this been tested?
---------------------------
**Devices/Simulators:** iMac19,1

**macOS Version:** 10.15.7 (19H2)

**Sequel-Ace Version:** latest main

### CODE REVIEW

**Review by Kaspik — APPROVED** [review]

**Review by Jason-Morcos — CHANGES_REQUESTED** [review]
Hmmm I'm getting a crash on window close on this branch.

Screen Shot 2020-10-24 at 10 50 19

**Comment by Jason-Morcos** [comment]
Screen Shot 2020-10-24 at 10 54 04

**Comment by jamesstout** [comment]
Think I fixed it.

**Review by Jason-Morcos — APPROVED** [review]
Indeed looks fixed!

**Pull request merged**
