### PR TITLE
#changed monospaced numbers to table columns

### PR DESCRIPTION
**Pull request by stefanfuerst**
## Changes:
Numbers will be displayed with an uniform width in tables, increasing the readability 

## Tested:
- Processors:
  - [X] Apple Silicon
- macOS Versions:
  - [X] 12.3 (Monterey)
- Localizations:
  - [X] English
  - [X] German

## Screenshots:

New
image
Old
image

### CODE REVIEW

**Comment by luis-** [comment]
I'm just curious, is the font setting found under general tab of preferences not working for you?
I've been using monospace fonts for as long as I can remember.

**Comment by stefanfuerst** [comment]
> I'm just curious, is the font setting found under general tab of preferences not working for you?
> I've been using monospace fonts for as long as I can remember.

I don't think you should have to pick another font to achieve better readability. Also changing the typography option has no effect on my machine.
Fonts 2022-04-13 18-24-51

**Review by Jason-Morcos — COMMENTED** [review]
This looks okay to me, but I'm not sure if there are any unintended side-effects of this change or if it could introduce negative performance implications, particularly when loading really big tables of data.

Additionally, it may be worth considering writing this change in Swift instead. We're trying to work towards a full-swift codebase so adding new Objective-C Classes runs counter to that objective.

@Kaspik do you have any thoughts?

**Comment by Kaspik** [comment]
I'm not sure how hard Swift version will be but definitely preferred. 🙊

**Comment by Jason-Morcos** [comment]
Looks like tests are also currently failing on this one. Converting into a draft but happy to take a look again once it's passing and ready to go!

**Pull request closed without merging**
