### PR TITLE
#fixed - Application quits on closing last DB connection

### PR DESCRIPTION
**Pull request by NiklasBr**
Adhere to Mac OS Human Interface Guidelines and improve user experience by not quitting the application when closing a window.

## Changes:
- `applicationShouldTerminateAfterLastWindowClosed` to `false`

## Closes following issues:
- Closes:  #2035

## Tested:
- Processors:
  - [ ] Intel
  - [x] Apple Silicon
- macOS Versions:
  - [ ] 10.13.x (High Sierra)
  - [ ] 10.14.x (Mojave)
  - [ ] 10.15.x (Catalina)
  - [ ] 11.x (Big Sur)
  - [ ] 12.x (Monterey)
  - [ ] 13.x (Ventura)
  - [x] 14.x (Sonoma)
- Localizations:
  - [ ] English
  - [ ] Spanish
  - [ ] Other (please specify) n/a
- Xcode Version:
  
## Screenshots:
n/a

## Additional notes:

I considered removing the entire `applicationShouldTerminateAfterLastWindowClosed` block since that would also return to the default Mac OS behaviour, which is not to quit the app when closing one of it's windows, but I think the intent is clearer when being explicit about it.

### CODE REVIEW

**Comment by Kaspik** [comment]
Have you seen why this was added and what it fixed? https://github.com/Sequel-Ace/Sequel-Ace/pull/2001

**Comment by NiklasBr** [comment]
Looks like it was a way to treat a symptom rather than fixing the underlying issue, no? In any case I can't reproduce the linked issue with this change.

**Comment by Jason-Morcos** [comment]
Not sure how we best move forward here - what if this was a new option in settings to allow the app to stay open after closing last window? That way people can pick which behavior they'd prefer?

**Comment by Jason-Morcos** [comment]
Closing due to lack of recent activity - happy to reopen down the road

**Comment by NiklasBr** [comment]
I had a summer vacation and you just closed this issue ... :(

**Comment by Jason-Morcos** [comment]
Happy to reopen if we want to resume the discussion! :)

**Comment by NiklasBr** [comment]
Yes, please reopen.

**Comment by Kaspik** [comment]
I don't see a reason really why to reopen one-line fix if the one-line is wrong (per my comment why that was added in the first place).

Happy to review a PR that fixes the reason why tis was added / fixes it differently.

**Comment by NiklasBr** [comment]
Given that: 

1. the original change only hid a symptom,
2. and introduced a new issue,
3. and the grandparent issue cannot be reproduced any more (potentially fixed upstream?)

Can I petition that you reconsider?

**Comment by Jason-Morcos** [comment]
Opening to foster open discussion - but I think we'll need to reach a consensus here before any change is made

**Comment by NiklasBr** [comment]
Thanks for still considering!

> Not sure how we best move forward here - what if this was a new option in settings to allow the app to stay open after closing last window? That way people can pick which behavior they'd prefer?

Options/settings adds complexity and "costs" future support and testing, if you are okay with that I am not entirely opposed. But sticking with operating system defaults is "free" in a sense.

In addition to my earlier questions, what were the design considerations you took when you added a confirmation on **Quit** (`CMD`+`Q`) which is an intentional action to quit the application, but not the same confirmation modal dialogue on **Close** (`CMD`+`W`) which is an action to close a window?

Screenshot 2024-08-12 at 19 33 06

I think knowing more about the context of that choice of logic could help us to come to a better understanding.

**Comment by Jason-Morcos** [comment]
@Kaspik might have more info here - but my understanding is that we'd like to take at least one stab at fixing the underlying memory issue. If we have a theory and can apply that theoretical fix, then we could try reverting the quit-on-last-window-closed change.

**Comment by kinglozzer** [comment]
I believe the original issue (https://github.com/Sequel-Ace/Sequel-Ace/issues/1975) is actually caused by the crash handler. I’m basing that on a combination of:

1) the crash reports in the issue pointing to Microsoft App Center;
2) the implementation that seems to connect Sequel Ace to the App Center ([`ReportExceptionApplication.m`](https://github.com/Sequel-Ace/Sequel-Ace/blob/205b3d2324b4b6884959259fe9651f431136004d/Source/Controllers/Other/ReportExceptionApplication.m)), and;
3) my own testing below


Using `4.0.16` I can reproduce the original issue consistently (multiple times, in < 5 minutes), but if I disable the “_Share anonymized usage analytics with developers_” option in preferences then the crash no longer occurs, even after 30 minutes of waiting.

I haven’t dug into it any further at this stage, but there’s _something_ wrong in [`ReportExceptionApplication.m`](https://github.com/Sequel-Ace/Sequel-Ace/blob/205b3d2324b4b6884959259fe9651f431136004d/Source/Controllers/Other/ReportExceptionApplication.m).

**Comment by NiklasBr** [comment]
> Kaspik might have more info here

I would like to know more :)

> Using `4.0.16` I can reproduce the original issue consistently (multiple times, in < 5 minutes), but if I disable the “_Share anonymized usage analytics with developers_” option in preferences then the crash no longer occurs, even after 30 minutes of waiting.

Matches my experience, I did not have it checked and it did not crash:

Screenshot 2024-10-07 at 15 02 52

**Comment by jonatansmedsgard** [comment]
My habit has always been to close the current active window with (`CMD`+`W`) and afterwards open a new connection to another DB with (`CMD`+`N`). Unfortunately this is no longer possible so I would gladly appreciate if this pull request is accepted. For me this change is more annoying than the crash it tried to avoid.

**Comment by Kaspik** [comment]
I think all was said in the issues, and the PR can be closed for now in the state it is.

**Comment by NiklasBr** [comment]
@Kaspik is it okay if you elaborate on the design decision I asked for above where @Jason-Morcos refereed to your knowledge?

**Comment by Kaspik** [comment]
I think the modal was just forgotten and should be shown in both cases, my bad. :)

**Review by Jason-Morcos — APPROVED** [review]
Given the previous release appears to have fixed the duplicate connection issue, I think it's safe to try again assuming the memory leak was resolved by that duplicate connection fix PR.

Folks can still manually quit the app if needed if memory spikes

**Pull request merged**
