### PR TITLE
Add prompt if app should close before termination #added

### PR DESCRIPTION
**Pull request by Kaspik**
## Changes:
- Add prompt to the user when quitting the app

## Closes following issues:
- Closes: https://github.com/Sequel-Ace/Sequel-Ace/issues/1971

## Tested:
- Processors:
  - [ ] Intel
  - [x] Apple Silicon
- macOS Versions:
  - [ ] 10.13.x (High Sierra)
  - [ ] 10.14.x (Mojave)
  - [ ] 10.15.x (Catalina)
  - [ ] 11.x (Big Sur)
  - [ ] 12.x (Monterey)
  - [ ] 13.x (Ventura)
  - [x] 14.x (Sonoma)
- Localizations:
  - [x] English
  - [ ] Spanish
  - [ ] Other (please specify)
- Xcode Version: 15.3

### CODE REVIEW

**Review by Jason-Morcos — COMMENTED** [review]
Looks good but IMO I think we should make this an optional setting and not enable across the board (or at least give folks an easy way to turn it off)
I know for me, personally, I find these kind of extra confirmations tedious and annoying 😆

**Comment by Kaspik** [comment]
Feel free to checkout the branch and add it to settings, enabled by default. :)

**Comment by Jason-Morcos** [comment]
> Feel free to checkout the branch and add it to settings, enabled by default. :)

Will add to my to-do list! Might not get to it until next weekend. :)

**Comment by Kaspik** [comment]
Lets get it in in the meantime so I fon't have to rebase, we are not releasing anyways :)

**Review by Jason-Morcos — APPROVED** [review]

**Pull request merged**
