### PR TITLE
401 - Universal Binaries for libcrypto and libssl

### PR DESCRIPTION
**Pull request by Jason-Morcos**
From @jamesstout #401

### CODE REVIEW

**Comment by Jason-Morcos** [comment]
Hmmm we have an issue here - doesn't compile for x86 @jamesstout @Kaspik 
Perhaps I made an error here?

**Comment by Jason-Morcos** [comment]
There's something wrong related to the second build script on SPMySQLFramework project I think. Something is funky about paths to libs

**Comment by Kaspik** [comment]
Careful with these system libs, they are completely changed in Big Sur:

```

New in macOS Big Sur 11 beta, the system ships with a built-in dynamic linker cache of all system-provided libraries. As part of this change, copies of dynamic libraries are no longer present on the filesystem. Code that attempts to check for dynamic library presence by looking for a file at a path or enumerating a directory will fail. Instead, check for library presence by attempting to dlopen() the path, which will correctly check for the library in the cache. (62986286)
```

https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11-beta-release-notes/

**Comment by Jason-Morcos** [comment]
> Careful with these system libs, they are completely changed in Big Sur:
> 
> `New in macOS Big Sur 11 beta, the system ships with a built-in dynamic linker cache of all system-provided libraries. As part of this change, copies of dynamic libraries are no longer present on the filesystem. Code that attempts to check for dynamic library presence by looking for a file at a path or enumerating a directory will fail. Instead, check for library presence by attempting to dlopen() the path, which will correctly check for the library in the cache. (62986286)`
> 
> https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11-beta-release-notes/

Okay but how do we fix it? 😆

**Comment by Kaspik** [comment]
`brew upgrade openssl@1.1` solved the issue for me :)

**Comment by Kaspik** [comment]
Btw did you try to add OpenSSL into the project itself? 

https://github.com/x2on/OpenSSL-for-iPhone

**Comment by Kaspik** [comment]
There is also an option to integrate project into our workspace - https://github.com/sqlcipher/openssl-xcode

**Comment by Jason-Morcos** [comment]
> Btw did you try to add OpenSSL into the project itself? 
> 
> 
> 
> https://github.com/x2on/OpenSSL-for-iPhone

Didn't try that! Will definitely need to get this resolved for Apple silicon native support. I think this mag be the only big hurdle though.

**Comment by Jason-Morcos** [comment]
> `brew upgrade openssl@1.1` solved the issue for me :)

^ this feels like a jank fix to me 😂 is it?

**Comment by Kaspik** [comment]
> > `brew upgrade openssl@1.1` solved the issue for me :)
> 
> ^ this feels like a jank fix to me 😂 is it?

That fixes only your local machine 😂 
You need to include the libraries in the project and setup them correctly. 😄

**Comment by Jason-Morcos** [comment]
> > > `brew upgrade openssl@1.1` solved the issue for me :)
> > 
> > 
> > ^ this feels like a jank fix to me 😂 is it?
> 
> That fixes only your local machine 😂
> You need to include the libraries in the project and setup them correctly. 😄

^ I'm really not sure how to do that lol. We could include that Xcode project mentioned, but I would rather just include the compiled universal libraries if that's possible. Unless there is an advantage to an Xcode include? Those looked unofficial

**Comment by Kaspik** [comment]
I'll take care of that later, we still have time before first ARM mac is a thing. Keep this draft open :)

**Pull request closed without merging**
