### PR TITLE
More permissions

### PR DESCRIPTION
**Pull request by jamesstout**
What does this implement/fix? Explain your changes.
---------------------------------------------------

- Fix selection of SSL keys/certs
- Unit tests for good/bad keys/certs
- Improved key/cert header/footer validation
- Re-Request Secure Access to all our stored bookmarks
- `stopAccessingSecurityScopedResources` in ExportController
- Don't copy keys/certs to `.keys `- we don't need to now, we have the secure bookmarks.

Does this close any currently open issues?
------------------------------------------
https://github.com/Sequel-Ace/Sequel-Ace/issues/52

Where has this been tested?
---------------------------

**macOS Version:** 10.15.5

**Sequel-Ace Version:** 2.1.0

### CODE REVIEW

**Comment by Jason-Morcos** [comment]
Setting my SSH key on this branch (and saving), it works flawlessly _until_ I quit and re-open Sequel Ace. From then on I get a connection error until I reselect the key. 
Screen Shot 2020-06-25 at 01 43 38
Nothing useful in show detail, except that it is clear that the -i flag is being properly set

My hunch is something about regaining access to bookmarks on fresh start is funky?

**Comment by jamesstout** [comment]
@Jason-Morcos Can't replicate. Steps:

1. SSH tab, fill in the details, choose and save SSH key.
2. Connect - OK.
3. Close app
4. Restart app, try to connect to the same fave - OK for me. I'll upload a vid to slack.

**Comment by jamesstout** [comment]
Do you definitely have the latest code with `reRequestSecureAccess` in `SPConnectionController.m`

**Comment by Jason-Morcos** [comment]
@jamesstout It turns out when I select a key it's not being added to my bookmarks. This is the error:

Screen Shot 2020-06-25 at 18 23 12
Screen Shot 2020-06-25 at 18 23 03

**Comment by jamesstout** [comment]
Very strange. The logs clearly say:

- Got access to key
- Not been here before so let's create a bookmark
- Can't open key

Debugging:
Oh, just seen your slack msgs .. will look.

**Pull request merged**
