### PR TITLE
Fix for crash on tables with invisible columns #fixed

### PR DESCRIPTION
**Pull request by Jason-Morcos**
## Changes:
- Load back each column in the table instead of *

## Closes following issues:
- Closes: maybe #1360 

## Tested:
- Processors:
  - [ ] Intel
  - [x] Apple Silicon
- macOS Versions:
  - [ ] 10.12.x (Sierra)
  - [ ] 10.13.x (High Sierra)
  - [ ] 10.14.x (Mojave)
  - [ ] 10.15.x (Catalina)
  - [ ] 11.x (Big Sur)
  - [x] 12.x (Monterey)
- Localizations:
  - [x] English
  - [ ] Spanish
  - [ ] Other (please specify)
- Xcode Version: 13.3

### CODE REVIEW

**Comment by Jason-Morcos** [comment]
@aaronjheng @Sequel-Ace/all does anyone have a MySQL 8 table with invisible columns they could test this against? I've only got 5.7 setups going right now

**Review by Kaspik — APPROVED** [review]
No MySQL 8 here

**Comment by aaronjheng** [comment]
@Jason-Morcos I have a local instance. But I don't know how to build and test this fix.

**Comment by gduh** [comment]
@Jason-Morcos Your fix is ok, SACE no longer crashes. But invisible fields are still display.

In the query tab, `select * from table` will only send visible columns. If you want to show the invisible columns, you must specified them explicitly, like this `select col1, col2, myInvisibleColumn,...  from table`

The both documentations (MySQL & MariaDB) say : 
_Since SELECT * does not return the invisible columns, new tables or views created in this manner will have no trace of the invisible columns. If specifically referenced in the SELECT statement, the columns will be brought into the view/new table, but the INVISIBLE attribute will not._

The question is : on the 'Content' tab, should we send all the columns or only the visible columns? Maybe a new parameter in 'Preferences --> Table --> Show invisible columns in Content tab' ?

**Review by gduh — APPROVED** [review]

**Comment by Jason-Morcos** [comment]
> @Jason-Morcos Your fix is ok, SACE no longer crashes. But invisible fields are still display.
> 
> In the query tab, `select * from table` will only send visible columns. If you want to show the invisible columns, you must specified them explicitly, like this `select col1, col2, myInvisibleColumn,... from table`
> 
> The both documentations (MySQL & MariaDB) say : _Since SELECT * does not return the invisible columns, new tables or views created in this manner will have no trace of the invisible columns. If specifically referenced in the SELECT statement, the columns will be brought into the view/new table, but the INVISIBLE attribute will not._
> 
> The question is : on the 'Content' tab, should we send all the columns or only the visible columns? Maybe a new parameter in 'Preferences --> Table --> Show invisible columns in Content tab' ?
> 
> Changes are required inside the object `Fields` (because the Invisible keyword is not present) in order to exclude (or not) the invisible columns from the `select`. Also, I think it should appear in the 'Structure' tab in the column `Extra` as mentioned in the MySQLM documentation.
> 
> image

Totally agree with everything you said, @gduh! I think adding more complete support for INVISIBLE columns would be great - both showing these columns as such in the structure tab and the the option of whether or not to show them in content.

Because the current behavior is a crash, I'm going to push this PR as-is as a bug fix in the next Sequel Ace release. If you'd like to expand support for INVISIBLE columns in a future PR, I really think that's a great idea!

**Pull request merged**
