### PR TITLE
Move files to match locations in organizer

### PR DESCRIPTION
**Pull request by clayreimann**
What does this implement/fix? Explain your changes.
---------------------------------------------------
This is not so much a code change as moving files around to match the structure of the organizer. I was poking around the code base and was trying to figure out the relative complexity of the project and it's components. Since the source was all in one directory (as was the default on older versions of XCode) it was hard to estimate with tools like `cloc` and `scc`. So I mapped the folders in the Organizer onto physical directories (the default on newer versions of XCode) to get a better sense of how much code was where.

**Results**
```
Production Code 
──────────────────────────────────────────────────────────────────────────────────────────────
Language                              Files     Lines   Blanks  Comments     Code   Complexity
──────────────────────────────────────────────────────────────────────────────────────────────
C Header                                174     14938     1906      7110     5922           36
Objective C                             158    102209    16917     17466    67826        16088
Swift                                     3       175       20        46      109           11
C                                         2       331       52       136      143           16
LEX                                       2       781       35       596      150            0
──────────────────────────────────────────────────────────────────────────────────────────────
Total                                   339    118434    18930     25354    74150        16151
──────────────────────────────────────────────────────────────────────────────────────────────

──────────────────────────────────────────────────────────────────────────────────────────────
Directory                             Files     Lines   Blanks  Comments     Code   Complexity
──────────────────────────────────────────────────────────────────────────────────────────────
Source/Controllers                      139     77523    12867     14786    49870        10451
Frameworks                              219     36751     4973     10324    21454         2235
Source/Views                             65     14404     1917      3487     9000         1760
Source/Other                             85     15520     2152      5230     8138         1507
Source/ThirdParty                        27      7606     1471       972     5163         1988
Source/Model                             21      3319      518       826     1975          445

──────────────────────────────────────────────────────────────────────────────────────────────
Directory                             Files     Lines   Blanks  Comments     Code   Complexity
──────────────────────────────────────────────────────────────────────────────────────────────
Source/Controllers                      139     77523    12867     14786    49870        10451
Source/Controllers/MainViewControllers   25     28051     4761      4861    18429         4200
Source/Controllers/SubviewControllers    37     20118     3444      3927    12747         2808
Source/Controllers/DataExport            28      8212     1442      2253     4517          988
Source/Controllers/DataImport             4      4501      589       414     3498          604
Source/Controllers/DataControllers       12      5247      641      1152     3454          387
Source/Controllers/BundleSupport          6      3483      595       475     2413          584
Source/Controllers/Preferences           19      3470      628       858     1984          239
Source/Controllers/Window                 2      1027      195       281      551           66
Source/Controllers/Other                  4       751      102       232      417           94

```

Where has this been tested?
---------------------------
**macOS Version:** 10.15.6

**Sequel-Ace Version:** 2.2.0

### CODE REVIEW

**Review by Jason-Morcos — COMMENTED** [review]
This is probably a very good change to make, but we might want to wait to merge this until all the other open PRs are merged to decrease the chance of conflicts!
Nice organizational improvement though, I like it.

**Comment by Jason-Morcos** [comment]
We're doing a little branch cleanup. See readme for the new branches. I would gladly take a look at this PR after branch cleanup is made if un-conflicted and pointed at the new `main` branch

**Comment by jamesstout** [comment]
> **Results**
> 
> ```
> Production Code 
> ──────────────────────────────────────────────────────────────────────────────────────────────
> Language                              Files     Lines   Blanks  Comments     Code   Complexity
> ──────────────────────────────────────────────────────────────────────────────────────────────
> C Header                                174     14938     1906      7110     5922           36
> Objective C                             158    102209    16917     17466    67826        16088
> Swift                                     3       175       20        46      109           11
> C                                         2       331       52       136      143           16
> LEX                                       2       781       35       596      150            0
> ──────────────────────────────────────────────────────────────────────────────────────────────
> Total                                   339    118434    18930     25354    74150        16151
> 

@clayreimann What command did you use to generate this nice table? Thanks

**Comment by stychos** [comment]
> > **Results**
> > ```
> > Production Code 
> > ──────────────────────────────────────────────────────────────────────────────────────────────
> > Language                              Files     Lines   Blanks  Comments     Code   Complexity
> > ──────────────────────────────────────────────────────────────────────────────────────────────
> > C Header                                174     14938     1906      7110     5922           36
> > Objective C                             158    102209    16917     17466    67826        16088
> > Swift                                     3       175       20        46      109           11
> > C                                         2       331       52       136      143           16
> > LEX                                       2       781       35       596      150            0
> > ──────────────────────────────────────────────────────────────────────────────────────────────
> > Total                                   339    118434    18930     25354    74150        16151
> > ```
> 
> @clayreimann What command did you use to generate this nice table? Thanks

it's `cloc`, available in Homebrew

**Comment by jamesstout** [comment]
I was wondering how you get the output by directory

**Comment by clayreimann** [comment]
I committed the script I used to generate the results, I think the by directory table I got by cherrypicking the totals line for each directory. Sorry for the lack of magic bullet 🙂

**Comment by stychos** [comment]
Ahh.. don't seen the elephant, it's in `complexity/take-snapshot.sh` in your commit, using scc.

**Comment by jamesstout** [comment]
Thanks

**Pull request closed without merging**
