### PR TITLE
Copy Themes And Default Bundles on build

### LINKED ISSUE #100: Missing Query Editor themes
- Sequel Ace Version: 2.1.0 beta 4
- macOS Version: 10.15
- MySQL Version: N/A

**Description**
I see no themes available in Preferences > Query Editor.

**Steps To Reproduce**
image

**Expected Behaviour**
There should be a few themes there... Not sure how many.

### PR DESCRIPTION
**Pull request by Jason-Morcos**
Re-adds copying default themes and bundles to fix (possibly) #100 and #36 as mentioned by https://github.com/Sequel-Ace/Sequel-Ace/issues/36#issuecomment-649348945

@jamesstout @gboudreau Does this fix all the issues with Themes and Bundles for you both?

### CODE REVIEW

**Comment by gboudreau** [comment]
Yes, that seems to do it.

**Comment by jamesstout** [comment]
> @jamesstout @gboudreau Does this fix all the issues with Themes and Bundles for you both?

If you already have the bundles, or run the app twice, you get duplicated Bundles, but not Themes:

Screenshot 2020-06-26 at 3 01 26 PM
Screenshot 2020-06-26 at 3 01 33 PM

Weird that it only duplicates once.

Something up with this code:

https://github.com/Sequel-Ace/Sequel-Ace/blob/21f5f1ec0b2e16e718e0b41e396a3af1a310c7c9/Source/SPAppController.m#L1682-L1684

**Comment by jamesstout** [comment]
It doesn't duplicate the bundles on the filesystem, just the menu items. We could go through the code to figure out why it's duplicating them, or just remove dupes at the end of the `reloadBundles` method. I'd like to know why really...

**Comment by gboudreau** [comment]
I don't see them duplicated myself.
image

**Comment by jamesstout** [comment]
The inconsistencies are driving me mad

**Comment by Jason-Morcos** [comment]
@jamesstout Am having duplicated bundles issue too. Will make a separate issue to fix in 2.1.1.

**Comment by Jason-Morcos** [comment]
Made an issue for this. I didn't read some of this thread before investigating so I duplicated some of @jamesstout's research but came to the same conclusions lol. https://github.com/Sequel-Ace/Sequel-Ace/issues/119

**Pull request merged**
