### PR TITLE
GitHub Pages Documentation

### PR DESCRIPTION
**Pull request by stychos**
This pull request is related to https://github.com/Sequel-Ace/Sequel-Ace/issues/24 and to #43 

Documentation is got from https://sequelpro.com/docs and slightly adapted.

Work in progress for concepts review. Live [here.](https://stychos.github.io/sequel-ace/)

To do:

- [x] Launch GitHub Pages
- [ ] <del>Getting Connected Section</del> Revise!
- [x] Making Queries & Query Favorites Pages
- [x] Keyboard Shortcuts Page
- [ ] Reference Section
- [ ] Bundles Section
- [ ] Contribute Section
- [ ] Usage Screenshots
- [ ] Verify all in-app links
- [ ] Download from AppStore link

Looks like in `docs/` directory it works only from `master` branch.

### CODE REVIEW

**Comment by Jason-Morcos** [comment]
Gonna merge! @stychos should we create a project with issues to do the remaining starting documentation things?

**Comment by stychos** [comment]
@Kaspik exactly that thing I trying to resolve now :)

**Comment by stychos** [comment]
@Jason-Morcos I think so.

**Comment by Jason-Morcos** [comment]
https://sequel-ace.com

**Pull request merged**
